
> book-vite-react@1.0.0 dev
> concurrently "npm run server" "npm run client"

[0] 
[0] > book-vite-react@1.0.0 server
[0] > nodemon server
[0] 
[1] 
[1] > book-vite-react@1.0.0 client
[1] > npm run dev --prefix ./client
[1] 
[0] [33m[nodemon] 3.0.3[39m
[0] [33m[nodemon] to restart at any time, enter `rs`[39m
[0] [33m[nodemon] watching path(s): *.*[39m
[0] [33m[nodemon] watching extensions: js,mjs,cjs,json[39m
[0] [32m[nodemon] starting `node server.js`[39m
[0] Server started on 80
[1] 
[1] > client@0.0.0 dev
[1] > vite --host
[1] 
[0] [32m[nodemon] restarting due to changes...[39m
[0] [32m[nodemon] starting `node server.js`[39m
[1] 
[1]   VITE v5.0.12  ready in 375 ms
[1] 
[1]   âžœ  Local:   http://localhost:80/
[1]   âžœ  Network: http://172.31.22.231:80/
[0] node:events:496
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::80
[0]     at Server.setupListenHandle [as _listen2] (node:net:1872:16)
[0]     at listenInCluster (node:net:1920:12)
[0]     at Server.listen (node:net:2008:7)
[0]     at Function.listen (/home/ubuntu/book-vite-react/node_modules/express/lib/application.js:635:24)
[0]     at Object.<anonymous> (/home/ubuntu/book-vite-react/server.js:28:20)
[0]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[0]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[0]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[0]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1899:8)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 80
[0] }
[0] 
[0] Node.js v20.11.1
[0] [31m[nodemon] app crashed - waiting for file changes before starting...[39m
[0] [32m[nodemon] restarting due to changes...[39m
[0] [32m[nodemon] starting `node server.js`[39m
[0] node:events:496
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::80
[0]     at Server.setupListenHandle [as _listen2] (node:net:1872:16)
[0]     at listenInCluster (node:net:1920:12)
[0]     at Server.listen (node:net:2008:7)
[0]     at Function.listen (/home/ubuntu/book-vite-react/node_modules/express/lib/application.js:635:24)
[0]     at Object.<anonymous> (/home/ubuntu/book-vite-react/server.js:28:20)
[0]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[0]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[0]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[0]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1899:8)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 80
[0] }
[0] 
[0] Node.js v20.11.1
[0] [31m[nodemon] app crashed - waiting for file changes before starting...[39m
[0] Killed
[0] npm run server exited with code 137
Killed

> book-vite-react@1.0.0 dev
> concurrently "npm run server" "npm run client"

[1] 
[1] > book-vite-react@1.0.0 client
[1] > npm run dev --prefix ./client
[1] 
[0] 
[0] > book-vite-react@1.0.0 server
[0] > nodemon server
[0] 
[0] [33m[nodemon] 3.0.3[39m
[0] [33m[nodemon] to restart at any time, enter `rs`[39m
[0] [33m[nodemon] watching path(s): *.*[39m
[0] [33m[nodemon] watching extensions: js,mjs,cjs,json[39m
[0] [32m[nodemon] starting `node server.js`[39m
[0] Server started on 443
[1] 
[1] > client@0.0.0 dev
[1] > vite --host
[1] 
[0] [32m[nodemon] restarting due to changes...[39m
[0] [32m[nodemon] starting `node server.js`[39m
[1] 
[1]   VITE v5.0.12  ready in 364 ms
[1] 
[1]   âžœ  Local:   http://localhost:80/
[1]   âžœ  Network: http://172.31.22.231:80/
[0] Server started on 443
[0] API called from a desktop device.
[0] API called from a desktop device.
[0] API called from a mobile device.
[0] API called from a mobile device.
[0] API called from a desktop device.
[0] API called from a desktop device.
[1] (node:29255) Warning: An error event has already been emitted on the socket. Please use the destroy method on the socket while handling a 'clientError' event.
[1] (Use `node --trace-warnings ...` to show where the warning was created)
[1] 2:06:18 PM [vite] .env changed, restarting server...
[0] [32m[nodemon] restarting due to changes...[39m
[0] [32m[nodemon] starting `node server.js`[39m
[1] 2:06:18 PM [vite] server restarted.
[0] Server started on 443
Killed
